id: AF5067F51
title: 'The Magical Lasso: A Prayer of Aspiration to Accomplish Khecara'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:34:46.590074
  last_modified_at: 2022-03-01 00:34:46.590081
